latent: 3
neurons: 256
is_train: False
is_restart: False
name: NP
fout
fin: ./dat/LJ/ljgp_params.npy
batch: 128
epoches: 6000
lr: 0.00005
step_size: 2000
device: 0
Kmax: 10
alpha: 0.001
input_f_dim: 2
